<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/hoc_tang_cuong/thuc_hanh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [18]:
class game():
  def __init__(self, x_tom, y_tom, x_jerry, y_jerry, x_spike, y_spike, x_block, y_block): # tao doi tuong
    self.tom = (x_tom, y_tom)
    self.jerry = (x_jerry, y_jerry)
    self.spike = (x_spike, y_spike)
    self.block = (x_block, y_block)

  def set_V(self, x, y): # tao V
    self.V = np.zeros((x, y))
    self.V[self.block] = -100
    self.V[self.jerry] = 1
    self.V[self.spike] = -1
    self.df = pd.DataFrame(self.V)

  def action_tom(self, x_tom, y_tom):
    if (x_tom, y_tom) == self.block:
      print("dung tuong")
    elif (x_tom, y_tom) == self.spike:
      print("bi cho can")
    elif (x_tom, y_tom) == self.jerry:
      print("bat duoc con chuot")
      self.tom = (x_tom, y_tom)
    else:
      self.tom = (x_tom, y_tom)

  def display(self):
    self.showframe = pd.DataFrame(self.V)
    for _ in range(self.V.shape[0]):
      for __ in range(self.V.shape[1]):
        self.showframe.at[(_,__)]=" "

    self.showframe.at[self.jerry] = "J"
    self.showframe.at[self.spike] = "S"
    self.showframe.at[self.block] = "--"
    if self.tom == self.jerry:
      self.showframe.at[self.tom] = "w"
    else:
      self.showframe.at[self.tom] = "T"
    display(self.showframe)

  def get_pos_tom(self):
    print(self.tom)

  def move(self, x, y):
    up       = (x-1, y)
    down     = (x+1, y)
    left     = (x, y-1)
    right    = (x, y+1)
    moves    = [up, down, left, right]
    canMoves = []
    for move in moves:
        move_x, move_y = move
        if 0 <= move_x < self.V.shape[0] and 0 <= move_y < self.V.shape[1]:
              if move not in [self.block]:
                canMoves.append(move)
    return canMoves

  def allMoves(self):
    results = []
    for i in range(self.V.shape[0]):
      for j in range(self.V.shape[1]):
        obj = {(i, j): self.move(i, j)}
        results.append(obj)
    return results

  def addValue(self, value):
    values = []
    for _ in value:
        values.append(_)
    return values

  def updateValue(self, value, gamma, p_down):
    listValue = self.addValue(value)
    maxValue = 0
    if len(value) > 1:
        sumVal = len(value) - 1
    else:
        sumVal = len(value)
    result = []
    for i in range(len(listValue)):
        sum = 0
        x_i, y_i = listValue[i]
        for j in range(len(listValue)):
            x_j, y_j = listValue[j]
            if j == i:
                sum += 0.8 * gamma * self.V[x_i][y_i]
            else:
                sum += (p_down / sumVal) * gamma * self.V[x_j][y_j]
        result.append(sum)
    maxValue = max(result)
    return maxValue

  def qtable(self, gamma, p_down):
    for __ in range(30):
      for i in self.allMoves():
        for _ in i:
          if _ in (self.jerry, self.spike, self.block):
            continue
          value = i[_]
          self.V[_] = self.updateValue(value, gamma, p_down)
    return self.V

  def auto_move(self):
    up       = (self.tom[0]-1, self.tom[1])
    down     = (self.tom[0]+1, self.tom[1])
    left     = (self.tom[0], self.tom[1]-1)
    right    = (self.tom[0], self.tom[1]+1)

    results = self.move(self.tom[0], self.tom[1])
    arr = []
    for result in results:
      obj = {}
      obj = {"pos":result, "values":self.qtable()[result]}
      arr.append(obj)

    x, y = max(arr, key=lambda x:x['values'])['pos']
    if (x, y) == up:
      print("Di len")
      self.action_tom(x, y)
      self.get_pos_tom()
      self.display()
    elif (x, y) == down:
      print("Di xuong")
      self.action_tom(x, y)
      self.get_pos_tom()
      self.display()
    elif (x, y) == left:
      print("Qua trai")
      self.action_tom(x, y)
      self.get_pos_tom()
      self.display()
    elif (x, y) == right:
      print("Qua phai")
      self.action_tom(x, y)
      self.get_pos_tom()
      self.display()

    if (x, y) == self.jerry:
      return None

    self.auto_move()
    return None

In [19]:
x_t = 0
y_t = 0
x_j = 2
y_j = 3
x_s = 1
y_s = 3
x_b = 1
y_b = 1

gamma = 0.9
p = 0.8
p_down = 0.2

In [15]:
g = game(x_t, y_t, x_j, y_j, x_s, y_s, x_b, y_b)
g.set_V(3, 4)
display(pd.DataFrame(g.qtable(gamma, p_down)))

0           1         2         3
0  0.441401    0.399508  0.444522  0.140056
1  0.513180 -100.000000  0.549946 -1.000000
2  0.602399    0.708371  0.833249  1.000000

In [20]:
g.action_tom(0, 1)
g.display()
g.auto_move()

0   1  2  3
0      T      
1     --     S
2            J

Qua phai
(0, 2)


0   1  2  3
0         T   
1     --     S
2            J

Di xuong
(1, 2)


0   1  2  3
0             
1     --  T  S
2            J

Di xuong
(2, 2)


0   1  2  3
0             
1     --     S
2         T  J

Qua phai
bat duoc con chuot
(2, 3)


0   1  2  3
0             
1     --     S
2            w

In [ ]:
V = np.zeros((3, 4))
V

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# lock = [(0, 4), (0, 8),
#         (1, 4), (1, 6), (1, 8),
#         (2, 1), (2, 2), (2, 4), (2, 6), (2, 8),
#         (3, 1), (3, 6), (3, 8),
#         (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 8), (4, 9),
#         (5, 4)]
# target = [(0,11), (1,11)]
lock = [(1, 1)]
target = [(0, 4), (1, 4)]

In [ ]:
for i in lock:
  V[i] = -100
V[0, 3] = 1
V[1, 3] = -1

In [ ]:
for _ in V:
  print(_)

[0. 0. 0. 1.]
[   0. -100.    0.   -1.]
[0. 0. 0. 0.]


In [ ]:
def canMove(x, y, V, block_moves):
  up       = (x-1, y)
  down     = (x+1, y)
  left     = (x, y-1)
  right    = (x, y+1)
  moves    = [up, down, left, right]
  canMoves = []
  for move in moves:
      move_x, move_y = move
      if 0 <= move_x < V.shape[0] and 0 <= move_y < V.shape[1]:
            if move not in block_moves:
              canMoves.append(move)
  return canMoves

In [ ]:
def allMoves(V, block_moves):
  results = []
  for i in range(V.shape[0]):
    for j in range(V.shape[1]):
      obj = {(i, j): canMove(i, j, V, block_moves)}
      results.append(obj)
  return results;

In [ ]:
def addValue(value):
    allVal = []
    for val in value:
        allVal.append(val)
    return allVal

In [ ]:
def updateValue(value, gamma, V, p_down):
    listValue = addValue(value)
    maxValue = 0
    if len(value) > 1:
        sumVal = len(value) - 1
    else:
        sumVal = len(value)
    result = []
    for i in range(len(listValue)):
        sum = 0
        x_i, y_i = listValue[i]
        for j in range(len(listValue)):
            x_j, y_j = listValue[j]
            if j == i:
                sum += 0.8 * gamma * V[x_i][y_i]
            else:
                sum += (p_down / sumVal) * gamma * V[x_j][y_j]
        result.append(sum)
    maxValue = max(result)
    return maxValue

In [ ]:
moves = allMoves(V, lock)

In [ ]:
import pandas as pd

for __ in range(30):
  for i in moves:
    for _ in i:
      if(_ == (0,3) or _ == (1,3) or _ in lock):
         continue
      value = i[_]
      V[_] = updateValue(value, gamma, V, p_down)
  print(f'lan {__}')
  display(pd.DataFrame(V))

lan 0


0      1         2         3
0  0.0    0.0  0.720000  1.000000
1  0.0 -100.0  0.428400 -1.000000
2  0.0    0.0  0.308448  0.042083

lan 1


0           1         2         3
0  0.0    0.518400  0.805212  1.000000
1  0.0 -100.000000  0.517513 -1.000000
2  0.0    0.222083  0.396384  0.105397

lan 2


0           1         2         3
0  0.373248    0.646937  0.824801  1.000000
1  0.268739 -100.000000  0.539531 -1.000000
2  0.233467    0.327421  0.427416  0.127739

lan 3


0           1         2         3
0  0.514168    0.686407  0.830334  1.000000
1  0.412225 -100.000000  0.546308 -1.000000
2  0.355738    0.371772  0.438298  0.135575

lan 4


0           1         2         3
0  0.568413    0.700155  0.832182  1.000000
1  0.473290 -100.000000  0.548618 -1.000000
2  0.407688    0.388958  0.442213  0.138393

lan 5


0           1         2         3
0  0.589304    0.705246  0.832848  1.000000
1  0.497683 -100.000000  0.549449 -1.000000
2  0.428344    0.395495  0.443654  0.139431

lan 6


0           1         2         3
0  0.597360    0.707175  0.833096  1.000000
1  0.507201 -100.000000  0.549758 -1.000000
2  0.436374    0.397978  0.444193  0.139819

lan 7


0           1         2         3
0  0.600462    0.707912  0.833190  1.000000
1  0.510880 -100.000000  0.549874 -1.000000
2  0.439470    0.398923  0.444396  0.139965

lan 8


0           1         2         3
0  0.601655    0.708195  0.833226  1.000000
1  0.512296 -100.000000  0.549919 -1.000000
2  0.440660    0.399284  0.444474  0.140021

lan 9


0           1         2         3
0  0.602114    0.708303  0.833240  1.000000
1  0.512841 -100.000000  0.549935 -1.000000
2  0.441116    0.399422  0.444503  0.140042

lan 10


0           1         2         3
0  0.602290    0.708345  0.833245  1.000000
1  0.513050 -100.000000  0.549942 -1.000000
2  0.441292    0.399475  0.444515  0.140051

lan 11


0           1         2         3
0  0.602357    0.708361  0.833247  1.000000
1  0.513130 -100.000000  0.549944 -1.000000
2  0.441359    0.399495  0.444519  0.140054

lan 12


0           1         2         3
0  0.602383    0.708367  0.833248  1.000000
1  0.513160 -100.000000  0.549945 -1.000000
2  0.441385    0.399503  0.444521  0.140055

lan 13


0           1         2         3
0  0.602393    0.708369  0.833248  1.000000
1  0.513172 -100.000000  0.549946 -1.000000
2  0.441395    0.399506  0.444521  0.140055

lan 14


0           1         2         3
0  0.602397    0.708370  0.833248  1.000000
1  0.513177 -100.000000  0.549946 -1.000000
2  0.441398    0.399507  0.444522  0.140056

lan 15


0           1         2         3
0  0.602398    0.708371  0.833248  1.000000
1  0.513179 -100.000000  0.549946 -1.000000
2  0.441400    0.399508  0.444522  0.140056

lan 16


0           1         2         3
0  0.602399    0.708371  0.833248  1.000000
1  0.513179 -100.000000  0.549946 -1.000000
2  0.441400    0.399508  0.444522  0.140056

lan 17


0           1         2         3
0  0.602399    0.708371  0.833248  1.000000
1  0.513179 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 18


0           1         2         3
0  0.602399    0.708371  0.833248  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 19


0           1         2         3
0  0.602399    0.708371  0.833248  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 20


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 21


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 22


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 23


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 24


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 25


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 26


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 27


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 28


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

lan 29


0           1         2         3
0  0.602399    0.708371  0.833249  1.000000
1  0.513180 -100.000000  0.549946 -1.000000
2  0.441401    0.399508  0.444522  0.140056

In [ ]:
def nextStep(x, y):

  nextMove = ''
  up       = (x-1, y)
  down     = (x+1, y)
  left     = (x, y-1)
  right    = (x, y+1)

  listMoveNexts = canMove(x, y, V, lock)
  arr = []

  for listMoveNext in listMoveNexts:
    obj = {}
    obj = {"pos":listMoveNext, "values":V[listMoveNext]}
    arr.append(obj)

  maxKey = max(arr, key=lambda x:x['values'])['pos']

  if maxKey == up:
      next_move = '^'
  elif maxKey == down:
      next_move = 'v'
  elif maxKey == left:
      next_move = '<'
  elif maxKey == right:
      next_move = '>'

  df.at[x, y] = next_move

  i, j = maxKey

  if maxKey == (0, 3):
      return df
  nextStep(i, j, V, df)

  return df

In [ ]:
# nextStep(1, 2, V)
df = pd.DataFrame(V)
for move in moves:
  for item in move:
    if item not in lock+target:
      l,k = item
      nextStep(l, k, V, df)

display(df)

0      1  2  3
0  >      >  >  <
1  ^ -100.0  ^  ^
2  ^      >  ^  <

In [ ]:
for _ in lock:
  df.at[_[0], _[1]] = "--"
df.at[0, 3] = "O"
df.at[1, 3] = "X"
df

0   1  2  3
0  >   >  >  O
1  ^  --  ^  X
2  ^   >  ^  <