<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian $R^3$, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
A = np.array([5, 7, 14])
print(A)

[ 5  7 14]


Bài 2: Mở rộng không gian lên $R^15$, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [ ]:
A = np.array([i+1 for i in range(15)])
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3: Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian $R^n$ với n là số nguyên dương được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [ ]:
n = int(input("n: "))
A_ = np.random.randint(10, size=n)
print(A_)

n: 4
[7 5 6 5]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA=[7,-5,8]

In [ ]:
OA = np.array([7,-5,8])
OA_ = np.linalg.norm(OA)
print(OA)
print(OA_)

[ 7 -5  8]
11.74734012447073


Bài 5: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này ‖AB‖. Lưu ý: sử dụng Numpy.

In [ ]:
n = int(input("n: "))
A = np.random.randint(10, size=n)
print("vector A:", A)
B = np.random.randint(10, size=n)
print("vector B:", B)
AB = B-A
print(AB)
print(np.linalg.norm(AB))

n: 4
vector A: [6 5 8 5]
vector B: [1 0 0 2]
[-5 -5 -8 -3]
11.090536506409418


Bài 6: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 vector a & b và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.inner()

In [ ]:
n = int(input("n: "))
a = np.random.randint(10, size=n)
print("vector a:", a)
b = np.random.randint(10, size=n)
print("vector b:", b)

print(np.inner(a, b))

n: 3
vector a: [4 7 0]
vector b: [7 7 7]
77


Bài 7: Trong không gian $R^n$, hãy sinh ngẫu nhiên 2 vector a & b và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.cross()

In [ ]:
print(np.cross(a, b))

[ 49 -28 -21]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian $R^n$, số nguyên dương n được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a .

In [ ]:
n = int(input("n: "))
a = np.random.randint(10, size=n)
print("vector a:", a)
print("transpose a:", a.T)

n: 5
vector a: [2 7 0 3 7]
transpose a: [2 7 0 3 7]


Bài 9 - Kết hợp cấu trúc list với Numpy:
1. a = [1, 2, 3, 4, 5]
2. b = [[1], [2], [3], [4], [5]]

Hãy:
- Xuất a và b ra màn hình
- Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
- Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.

In [ ]:
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]

a_ = np.array(a)
b_ = np.array(b)

print(a)
print(b)

print("vector a:", a_)
print("vector b:", b_, sep = '\n')

print("transpose a:", a_.T)
print("transpose b:", b_.T)

[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
vector a: [1 2 3 4 5]
vector b:
[[1]
 [2]
 [3]
 [4]
 [5]]
transpose a: [1 2 3 4 5]
transpose b: [[1 2 3 4 5]]


Bài 10: Trong không gian $R^n$, hãy sinh ngẫu nhiên vector a và b, n là số nguyên dương nhập vào từ bàn phím. 

Hãy:

-Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình

-Thực hiện phép cộng 2 vector: a + b và xuất kết quả ra màn hình.

In [ ]:
n = int(input("n: "))
a = np.random.randint(10, size=n)
print("vector a:", a)
b = np.random.randint(10, size=n)
print("vector b:", b)

m = int(input("m: "))
print("a+m:", a+m)
print("a+b:", a+b)

n: 5
vector a: [7 3 8 0 9]
vector b: [6 8 3 5 9]
m: 10
a+m: [17 13 18 10 19]
a+b: [13 11 11  5 18]
