<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [1]:
import numpy as np
zz = "\n"
A =np.random.randint(-10, 10, (7, 5))
A

array([[  2,  -9, -10,   3,   8],
       [  1,  -9,   7,  -2,   3],
       [ -9,   8,   0,  -5,  -1],
       [ -9,  -6,   8,  -5,  -7],
       [ -7,  -7,  -8,  -2,  -2],
       [  6,   6,   3,   8,   7],
       [  8,  -1,  -7,   8,  -2]])

Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [2]:
A = np.zeros((6, 7))
A

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [3]:
A = np.random.randint(-10, 10, (7, 7))
A

array([[ 6, -7, -7, -8, -7, -3, -6],
       [ 2,  6, -1, -3, -4, -4, -6],
       [-1, -4, -9,  6,  0, -6,  1],
       [ 7,  5,  4, -7,  1, -4, -4],
       [ 4, -4,  6,  2,  1, -6, -8],
       [-3, -2, -4,  7,  4,  2, -3],
       [ 8, -9, -5, -8, -8, -6,  7]])

Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0 trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [4]:
A = np.zeros((6,6))
np.fill_diagonal(A, 15)
A

array([[15.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 15.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 15.]])

Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm numpy.triu(). Kết quả xuất ra màn hình.

In [5]:
A = np.random.randint(-10, 10, (8, 8))
A_ = np.triu(A,1)
A_

array([[  0,  -5,   3,  -7,   7,   5,   5,  -8],
       [  0,   0,  -4,   9,   1,  -7,   1,  -7],
       [  0,   0,   0,  -1,   4,   9, -10,  -8],
       [  0,   0,   0,   0,  -4,  -6,  -3,  -8],
       [  0,   0,   0,   0,   0,   8,   4,   2],
       [  0,   0,   0,   0,   0,   0,  -3,   1],
       [  0,   0,   0,   0,   0,   0,   0,   1],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [6]:
A_ = np.tril(A,-1)
A_

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  7,  -9,   0,   0,   0,   0,   0,   0],
       [  1,  -1,   4,   0,   0,   0,   0,   0],
       [ -8,   4,  -9,   6,   0,   0,   0,   0],
       [ -7,   0,   0,  -2,   7,   0,   0,   0],
       [ -6,  -2, -10,   7,  -2,  -8,   0,   0],
       [ -7,  -8,   4, -10,  -4,  -9,   3,   0]])

Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [7]:
I = np.identity(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:

In [8]:
# Sinh ngẫu nhiên 2 ma trận có kích thước 6x7. 
# Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
max1 = np.random.randint(-10, 10, (6, 7))
print("matrix A:", max1, sep=zz)
max2 = np.random.randint(-10, 10, (6, 7))
print("matrix B:", max2, sep=zz)
print("matrix C:", max1+max2, sep=zz)

matrix A:
[[  9  -5  -4  -4  -7   7  -2]
 [ -7  -4  -1   8   4   8   1]
 [  7  -1   2 -10   0   2 -10]
 [ -8  -9  -4   9   9   6   3]
 [ -1   4   7 -10  -8 -10  -7]
 [ -9   8   9   5   8  -9   8]]
matrix B:
[[-8 -2  4 -8 -7  2 -4]
 [ 4  7 -7  2 -7  7  5]
 [-5  9  3 -9 -3  9 -9]
 [ 2  6 -6 -3 -3  8 -6]
 [ 4 -6 -9 -3 -1  7 -1]
 [-5 -3  4  9 -2  5  9]]
matrix C:
[[  1  -7   0 -12 -14   9  -6]
 [ -3   3  -8  10  -3  15   6]
 [  2   8   5 -19  -3  11 -19]
 [ -6  -3 -10   6   6  14  -3]
 [  3  -2  -2 -13  -9  -3  -8]
 [-14   5  13  14   6  -4  17]]


In [9]:
# Sinh ngẫu nhiên 1 ma trận có kích thước 5x8. 
# Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này.
# Kết quả xuất ra màn hình.
max3 = np.random.randint(-10, 10, (5, 8))
print("matrix:", max3, sep=zz)
m = int(input("m: "))
print("matrix x m:", m*max3, sep=zz)

matrix:
[[  0  -2   2  -2   1   0   6   9]
 [ -3   4   1  -7  -5   5   7 -10]
 [  1  -6  -3  -2  -8  -6  -8  -6]
 [ -4  -8   8   4  -7   0   4  -1]
 [  9  -4  -5  -5  -7   6   4  -9]]
m: 4
matrix x m:
[[  0  -8   8  -8   4   0  24  36]
 [-12  16   4 -28 -20  20  28 -40]
 [  4 -24 -12  -8 -32 -24 -32 -24]
 [-16 -32  32  16 -28   0  16  -4]
 [ 36 -16 -20 -20 -28  24  16 -36]]


In [10]:
# Sinh ngẫu nhiên một ma trận có kích thước 3x7. 
# Thực hiện phép chuyển vị đối với ma trận này. 
# Xuất các ma trận này ra màn hình.
max4 = np.random.randint(-10, 10, (3, 7))
print("matrix:", max4, sep=zz)
print("transpose matrix:", max4.T, sep=zz)

matrix:
[[ -3  -6   7 -10   9   0  -6]
 [ -1   8   8   6  -5  -5   0]
 [  4  -8  -3  -9   8   6   6]]
transpose matrix:
[[ -3  -1   4]
 [ -6   8  -8]
 [  7   8  -3]
 [-10   6  -9]
 [  9  -5   8]
 [  0  -5   6]
 [ -6   0   6]]


In [11]:
# Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
# tiến hành nhân 2 ma trận này để thu được ma trận C5×3. 
# Xuất các ma trận trên ra màn hình. Gợi ý: sử dụng hàm numpy.dot()
max5 = np.random.randint(-10, 10, (5, 7))
print("matrix 5x7", max5, sep=zz)
max6 = np.random.randint(-10, 10, (7, 3))
print("matrix 3x7:", max6, sep=zz)
print("matrix c5x3:", np.dot(max5, max6), sep=zz)

matrix 5x7
[[ -7  -1   1   1   9   8  -7]
 [ -3   3  -8   5  -7   5  -7]
 [  3  -8  -4   7  -1  -7   5]
 [  0   3  -8 -10  -7   8   0]
 [ -8  -4  -6  -5   6 -10  -1]]
matrix 3x7:
[[ -7   6  -6]
 [ -8   7   8]
 [ -6  -4  -6]
 [  8   4   6]
 [  2  -5 -10]
 [  9   7   7]
 [ -8   3   2]]
matrix c5x3:
[[ 205  -59  -14]
 [ 172  104  211]
 [  18  -23  -45]
 [   2  104  138]
 [  14 -175 -110]]


In [12]:
# Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. 
# Gợi ý: sử dụng hàm numpy.linalg.inv()
max7 = np.random.randint(-10, 10, (5, 7))
print("matrix 5x7:", max7, sep=zz)
print("invertible matrix:", np.linalg.pinv(max7), sep=zz)

matrix 5x7:
[[  7  -9   8   6   1  -4   0]
 [  3   7   8  -6  -2  -8   5]
 [  5  -1   7  -6   3 -10   2]
 [  7  -5   2  -1   8   6  -1]
 [ -1   8   5   4  -9   2   9]]
invertible matrix:
[[ 0.04304004  0.10860279 -0.09700744  0.0428963  -0.03863706]
 [ 0.02697011  0.2225586  -0.21256542  0.01002079 -0.08250366]
 [ 0.06746285  0.14785186 -0.13027292  0.01678159 -0.04479592]
 [ 0.06680926  0.03772596 -0.08925801 -0.02229142 -0.01271092]
 [-0.03734671 -0.05246423  0.07157472  0.04240896  0.01020058]
 [-0.00955974  0.02847462 -0.06803     0.06325002  0.01191031]
 [-0.12158589 -0.34346183  0.37690501  0.02479648  0.21824446]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

In [13]:
# Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. 
# Hãy tạo ngẫu nhiên 1 vector hàng x có kích thước 1 × 8. 
# Kết quả xuất ra màn hình.
import numpy as np

row_vector = np.random.randint(-10, 10, (1,8))
row_vector

array([[ 5,  4, -6,  4, -8, -9,  6,  3]])

In [14]:
# Vector cột (column vector) thực chất là ma trận có kích thước m × 1. 
# Hãy tạo ngẫu nhiên 1 vector cột x có kích thước 8 × 1. 
# Kết quả xuất ra màn hình.
import numpy as np

column_vector = np.random.randint(-10, 10, (8,1))
column_vector

array([[ 9],
       [-4],
       [-3],
       [-1],
       [ 9],
       [ 2],
       [-8],
       [-3]])

Bài 10 - Hệ phương trình tuyến tính:

In [15]:
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
x

array([ 2.20833333, -2.58333333, -0.18333333])

In [16]:
#ma trận khả nghịch
A_inv = np.linalg.pinv(A)
x = np.dot(A_inv, y)
print("ma trận khả nghịch:")
x

ma trận khả nghịch:


array([ 2.20833333, -2.58333333, -0.18333333])