<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

func1dfunction (M,) -> (Nj…)

This function should accept 1-D arrays. It is applied to 1-D slices of arr along the specified axis.

Hàm này phải chấp nhận mảng 1-D. Nó được áp dụng cho các lát arr 1-D dọc theo trục được chỉ định.

axisinteger:

Axis along which arr is sliced.

Trục dọc theo arr được cắt.

arrndarray (Ni…, M, Nk…)

Input array.

Đầu vào mảng.

argsany:
Additional arguments to func1d.

kwargsany:
Additional named arguments to func1d.

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [28]:
import numpy as np
zz = "\n"
max = np.random.randint(-10, 10, (15, 17))
max

array([[ -3,   9,   6, -10,   9, -10,  -2,   2, -10,  -9,   7,  -8,  -7,
          3,   0,  -3,   9],
       [  0,  -9,  -3,  -7,  -4,  -1,  -6,   5,  -5,  -8,  -2,  -7,  -4,
          7,  -3,   3,  -6],
       [  5,   3,  -1,  -1,   6,   8,   5,   5,  -4,  -1,   1,  -8,  -4,
          2, -10,  -3,   2],
       [  7,  -4,   2,   3,  -3,   3,   2,  -3,   4,   0,  -5,   3,  -1,
          9,  -3,  -1,   4],
       [  6,  -4,  -8,   5, -10,   7,  -5,  -3,   4,  -2,  -1,   4,  -7,
         -1,   5,  -5, -10],
       [  8,  -2,   6,  -3,   4,   5,   8,  -7,  -6,  -6,  -3,  -3,   6,
          6,  -7, -10,   1],
       [  0,  -3,  -9,   8,   7,  -7,   4,  -7,  -1,  -2,   1,   9, -10,
         -7,   2,  -9,  -9],
       [  6,   1,   9,  -1,  -9,  -5,  -2,   4,   0,   3,   7,   5,  -4,
          0,   9,  -5,   3],
       [  9,   7,   0,   9,  -1,  -8,  -2,   0,   0,  -8,  -7,   1,  -3,
          2,  -6,   8,  -9],
       [  8,   6,  -3,   4,  -9,   8,   1,  -6,   8,   8,   0,  -2,   4,
         

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [27]:
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)

max_ = np.apply_along_axis(tim_gia_tri_lon_nhat, 1, max)
max_

array([8, 7, 8, 8, 9, 8, 7, 9, 8, 8, 7, 7, 9, 9, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [25]:
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)

max_ = np.apply_along_axis(tim_gia_tri_nho_nhat, 0, max)
max_

array([-10, -10,  -8, -10,  -9,  -9, -10, -10,  -9, -10, -10,  -7, -10,
        -6,  -6, -10, -10])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [69]:
def tinh_tong(vector_a):
  return np.sum(vector_a)

max_ = np.apply_along_axis(tinh_tong, 1, max)
max_

array([-17, -50,   5,  17, -25,  -3, -33,  21,  -8,   6, -27,  21,  -9,
         8,  -5])

Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [77]:
def tinh_tong_2(vector_a):
  return np.sum(vector_a[vector_a%2!=0])

max_ = np.apply_along_axis(tinh_tong_2, 1, max)
max_

array([ 15, -20,  13,   9,  -5, -17, -35,  17,   6, -30,  -9,  17,   9,
        10,  -1])