<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

func1dfunction (M,) -> (Nj…)

This function should accept 1-D arrays. It is applied to 1-D slices of arr along the specified axis.

Hàm này phải chấp nhận mảng 1-D. Nó được áp dụng cho các lát arr 1-D dọc theo trục được chỉ định.

axisinteger:

Axis along which arr is sliced.

Trục dọc theo arr được cắt.

arrndarray (Ni…, M, Nk…)

Input array.

Đầu vào mảng.

argsany:
Additional arguments to func1d.

kwargsany:
Additional named arguments to func1d.

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [14]:
import numpy as np

matrix = np.random.randint(-10, 10, (15, 17))
matrix

array([[  8, -10,   2,  -8,   1,   9,  -1,  -2,   2,   5,  -6,   9,   8,
          2,  -5,   5,   5],
       [ -8,   8,   9,  -8,   1,   4, -10,  -1,   6,   0,  -9,  -8,  -8,
          1,  -1,  -8,   7],
       [ -7,  -6,   2,  -6,   9,   2,  -3,   4,   6,  -3,  -4,   6,   4,
          8,  -7,  -6,  -4],
       [  0,   4,   6,   0,  -1,  -1,  -7, -10, -10,  -3,   4,  -5,  -7,
          9,  -4,   3,   2],
       [ -6,   5,   0,   8,  -1,  -2,  -4,  -3,  -8, -10,  -5,   5,  -6,
         -8,   6,   6,   4],
       [  5, -10,  -2,  -7,  -1,  -1,   5,   8,   2,   0,   1,  -3, -10,
         -1,   1,  -6,   4],
       [  2,   7,   4,   4,  -1,  -2,  -6,   7,  -8,  -7,  -1,   8,  -2,
          2,   8,  -4,   9],
       [ -1,  -9,   3,  -5,   4,  -9,  -4,   3, -10,   9,  -8,   6,   4,
        -10,  -3,  -1,  -8],
       [ -3,  -2,   3,   9,   4, -10,   6,  -9,   8,  -6,   4,  -8,   5,
          8,  -9,   5,  -4],
       [  3,  -3,   2,  -1,   6,   9,  -5,   9,   5,   0,   0,   4,  -9,
        -

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [15]:
def tim_gia_tri_lon_nhat(vector_a):
  return np.max(vector_a)

matrix_ = np.apply_along_axis(tim_gia_tri_lon_nhat, 1, matrix)
matrix_

array([7, 7, 9, 9, 8, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [16]:
def tim_gia_tri_nho_nhat(vector_a):
  return np.min(vector_a)

matrix_ = np.apply_along_axis(tim_gia_tri_nho_nhat, 0, matrix)
matrix_

array([ -8,  -7,  -9,  -9, -10, -10,  -8, -10, -10, -10,  -9, -10,  -9,
        -9, -10, -10, -10])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [17]:
def tinh_tong(vector_a):
  return np.sum(vector_a)

matrix_ = np.apply_along_axis(tinh_tong, 1, matrix)
matrix_

array([-10, -18,   5,  28,   6, -18,  34,   1,  -9, -21,  22,   2, -50,
         2,   5])

Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [18]:
def tinh_tong_2(vector_a):
  return np.sum(vector_a[vector_a%2!=0])

matrix_ = np.apply_along_axis(tinh_tong_2, 1, matrix)
matrix_

array([  6,   4,  21,  10,   0,  10,  24,   1,   7,  -7,  -8,  18, -30,
         8,  -3])