<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [46]:
import numpy as np
zz = "\n"
A =np.random.randint(-10, 10, (7, 5))
print(A)

[[  6   1  -5  -2  -6]
 [ -9  -1   5  -3   7]
 [-10  -3   5   8   8]
 [  0 -10  -8  -3   2]
 [  5  -4   0  -6   4]
 [ -7  -3   2  -2   0]
 [ -9   7   8   5  -1]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [47]:
A = np.zeros((6, 7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [48]:
A = np.random.randint(-10, 10, (7, 7))
print(A)

[[ -5   0  -1  -2  -5 -10   7]
 [-10   5  -1  -4  -7   2  -1]
 [  4  -5  -1  -1  -1   6  -3]
 [ -5  -1   6   4   9   0   8]
 [  1   2   3 -10   5   6   6]
 [ -6   7   4   2   5  -4  -5]
 [ -6   4   4   3   7   8   7]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0 trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [49]:
A = np.zeros((6,6))
np.fill_diagonal(A, 15)
print(A)

[[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm numpy.triu(). Kết quả xuất ra màn hình.

In [50]:
A = np.random.randint(-10, 10, (8, 8))
A_ = np.triu(A,1)
print(A_)

[[  0   9 -10   9   5   2  -6   3]
 [  0   0  -3  -3   3   7   3  -4]
 [  0   0   0   2  -4  -3   2   0]
 [  0   0   0   0   2   2  -8  -7]
 [  0   0   0   0   0   5  -3   8]
 [  0   0   0   0   0   0  -8   3]
 [  0   0   0   0   0   0   0  -7]
 [  0   0   0   0   0   0   0   0]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [51]:
A_ = np.tril(A,-1)
print(A_)

[[  0   0   0   0   0   0   0   0]
 [-10   0   0   0   0   0   0   0]
 [ -3   0   0   0   0   0   0   0]
 [  2   6  -1   0   0   0   0   0]
 [  5  -8  -6  -3   0   0   0   0]
 [  9 -10  -3   8   6   0   0   0]
 [ -4  -1   2   8   7   6   0   0]
 [  6   5   4  -4  -6   9  -4   0]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [52]:
I = np.identity(9)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:

In [53]:
# Sinh ngẫu nhiên 2 ma trận có kích thước 6x7. 
# Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
max1 = np.random.randint(-10, 10, (6, 7))
print("matrix A:", max1, sep=zz)
max2 = np.random.randint(-10, 10, (6, 7))
print("matrix B:", max2, sep=zz)
print("matrix C:", max1+max2, sep=zz)

matrix A:
[[  7   4  -9  -6  -7  -5   7]
 [ -7   5  -2   6  -6   2  -2]
 [  6  -6   0  -9  -4   7   5]
 [ -4 -10   2  -6  -5   3  -6]
 [  0  -4  -7   5 -10   1 -10]
 [  9   4  -9  -5   9  -4   2]]
matrix B:
[[ -5  -3  -9   7  -7  -2  -6]
 [  8 -10   6   5  -1  -5   7]
 [ -9   8  -5   2  -4   7   2]
 [ -5  -7  -9   5   3   2 -10]
 [  1   5   6   3   9   5 -10]
 [ -9   2   1  -7   7   2  -1]]
matrix C:
[[  2   1 -18   1 -14  -7   1]
 [  1  -5   4  11  -7  -3   5]
 [ -3   2  -5  -7  -8  14   7]
 [ -9 -17  -7  -1  -2   5 -16]
 [  1   1  -1   8  -1   6 -20]
 [  0   6  -8 -12  16  -2   1]]


In [54]:
# Sinh ngẫu nhiên 1 ma trận có kích thước 5x8. 
# Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này.
# Kết quả xuất ra màn hình.
max3 = np.random.randint(-10, 10, (5, 8))
print("matrix:", max3, sep=zz)
m = int(input("m: "))
print("matrix x m:", m*max3, sep=zz)

matrix:
[[  2   4   5  -7   2   4 -10   1]
 [  4   8  -2  -7   5  -3  -6  -5]
 [  1   6  -4  -8   7 -10  -6  -9]
 [  5  -4   9   1  -6   2   3   8]
 [  6   6   8  -5  -2   8   5  -3]]
m: 4
matrix x m:
[[  8  16  20 -28   8  16 -40   4]
 [ 16  32  -8 -28  20 -12 -24 -20]
 [  4  24 -16 -32  28 -40 -24 -36]
 [ 20 -16  36   4 -24   8  12  32]
 [ 24  24  32 -20  -8  32  20 -12]]


In [56]:
# Sinh ngẫu nhiên một ma trận có kích thước 3x7. 
# Thực hiện phép chuyển vị đối với ma trận này. 
# Xuất các ma trận này ra màn hình.
max4 = np.random.randint(-10, 10, (3, 7))
print("matrix:", max4, sep=zz)
print("transpose matrix:", max4.T, sep=zz)

matrix:
[[-10   8   6   5   2   1   0]
 [  4   0  -4  -5  -3   6  -4]
 [  3  -1  -3  -4  -4 -10  -6]]
transpose matrix:
[[-10   4   3]
 [  8   0  -1]
 [  6  -4  -3]
 [  5  -5  -4]
 [  2  -3  -4]
 [  1   6 -10]
 [  0  -4  -6]]


In [57]:
# Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
# tiến hành nhân 2 ma trận này để thu được ma trận C5×3. 
# Xuất các ma trận trên ra màn hình. Gợi ý: sử dụng hàm numpy.dot()
max5 = np.random.randint(-10, 10, (5, 7))
print("matrix 5x7", max5, sep=zz)
max6 = np.random.randint(-10, 10, (7, 3))
print("matrix 3x7:", max6, sep=zz)
print("matrix c5x3:", np.dot(max5, max6), sep=zz)

matrix 5x7
[[ -1  -3  -6   3   4   0  -5]
 [ -5  -1  -5   1  -2  -2  -6]
 [ -4   3   2   7   4   3   4]
 [  2   5   1 -10  -9   1   6]
 [  5   6   9  -6   1   2  -1]]
matrix 3x7:
[[ -1   8 -10]
 [ -5   9  -5]
 [  0   9   3]
 [  1   3  -4]
 [  4  -8  -6]
 [ -9   1 -10]
 [ -1   5 -10]]
matrix c5x3:
[[  40 -137   21]
 [  27 -107  128]
 [ -19   25  -91]
 [ -88  143  -18]
 [ -54  146  -45]]


In [67]:
# Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. 
# Gợi ý: sử dụng hàm numpy.linalg.inv()
max7 = np.random.randint(-10, 10, (5, 7))
print("matrix 5x7:", max7, sep=zz)
print("invertible matrix:", np.linalg.pinv(max7), sep=zz)

matrix 5x7:
[[ 4  4  1  2  2 -2  9]
 [-5 -2 -5 -7 -3 -7  4]
 [ 2  1 -2 -8  9  6  5]
 [-3  8 -6  7  9 -9 -2]
 [ 0  6  2  4  8 -9 -9]]
invertible matrix:
[[ 0.04747862 -0.017182    0.00385405 -0.03881405  0.03244911]
 [ 0.02584637 -0.00911012  0.00367056  0.01465413  0.00947989]
 [ 0.04649226 -0.00493488 -0.00911664 -0.07701761  0.0707516 ]
 [ 0.00580826 -0.05328242 -0.0436243   0.05329986 -0.04766247]
 [-0.00681179 -0.01347824  0.05140016  0.01716273  0.02189552]
 [-0.04049213 -0.05719189  0.02518434  0.02287807 -0.05728814]
 [ 0.06458118  0.0143601   0.00153724  0.00872091 -0.03350111]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

In [59]:
# Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. 
# Hãy tạo ngẫu nhiên 1 vector hàng x có kích thước 1 × 8. 
# Kết quả xuất ra màn hình.
import numpy as np

row_vector = np.random.randint(-10, 10, (1,8))
print(row_vector)

[[  0  -8   6   2   3   7  -8 -10]]


In [60]:
# Vector cột (column vector) thực chất là ma trận có kích thước m × 1. 
# Hãy tạo ngẫu nhiên 1 vector cột x có kích thước 8 × 1. 
# Kết quả xuất ra màn hình.
import numpy as np

column_vector = np.random.randint(-10, 10, (8,1))
print(column_vector)

[[ 6]
 [ 6]
 [ 7]
 [ 1]
 [-7]
 [ 0]
 [ 7]
 [ 6]]


Bài 10 - Hệ phương trình tuyến tính:

In [72]:
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [73]:
#ma trận khả nghịch
A_inv = np.linalg.pinv(A)
x = np.dot(A_inv, y)
print("ma trận khả nghịch:")
print(x)

ma trận khả nghịch:
[ 2.20833333 -2.58333333 -0.18333333]
