<a href="https://colab.research.google.com/github/nhattminh160901/Bai_Tap/blob/main/DoAn_2022/10_3_2022/numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Ghi chú: sau mỗi lần sinh ra giá trị cho vector, hãy cho biết số chiều của vector được sinh ra và
số chiều của vector chuyển vị của vector đó; cho biết kích thước của vector a và vector chuyển vị
của vector a.

Gợi ý: tham khảo ndim và shape.

In [57]:
import numpy as np

a = np.arange(0, 7, 1)
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5 6]
1
(7,)


In [58]:
a = np.linspace(0, 10, 7)
print(a)
print(a.ndim)
print(a.shape)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
1
(7,)


In [59]:
a = np.logspace(2, 3, 7)
print(a)
print(a.ndim)
print(a.shape)

[ 100.          146.77992676  215.443469    316.22776602  464.15888336
  681.29206906 1000.        ]
1
(7,)


In [60]:
a = np.random.rand(7)
print(a)
print(a.ndim)
print(a.shape)

[0.25806836 0.43532415 0.77268821 0.49341445 0.49682129 0.16852585
 0.75995887]
1
(7,)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận AT

In [61]:
A = np.arange(1, 11).reshape(-1, 1) * np.arange(1, 8)

print(A)
print(A.size)
print(A.ndim)
print(A.shape)

print(A.T)
print(A.T.size)
print(A.T.ndim)
print(A.T.shape)

[[ 1  2  3  4  5  6  7]
 [ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]
 [ 7 14 21 28 35 42 49]
 [ 8 16 24 32 40 48 56]
 [ 9 18 27 36 45 54 63]
 [10 20 30 40 50 60 70]]
70
2
(10, 7)
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]
 [ 4  8 12 16 20 24 28 32 36 40]
 [ 5 10 15 20 25 30 35 40 45 50]
 [ 6 12 18 24 30 36 42 48 54 60]
 [ 7 14 21 28 35 42 49 56 63 70]]
70
2
(7, 10)


In [62]:
A = np.linspace(1, 10, 10).reshape(-1, 1) * np.linspace(1, 10, 7)

print(A)
print(A.size)
print(A.ndim)
print(A.shape)

print(A.T)
print(A.T.size)
print(A.T.ndim)
print(A.T.shape)

[[  1.    2.5   4.    5.5   7.    8.5  10. ]
 [  2.    5.    8.   11.   14.   17.   20. ]
 [  3.    7.5  12.   16.5  21.   25.5  30. ]
 [  4.   10.   16.   22.   28.   34.   40. ]
 [  5.   12.5  20.   27.5  35.   42.5  50. ]
 [  6.   15.   24.   33.   42.   51.   60. ]
 [  7.   17.5  28.   38.5  49.   59.5  70. ]
 [  8.   20.   32.   44.   56.   68.   80. ]
 [  9.   22.5  36.   49.5  63.   76.5  90. ]
 [ 10.   25.   40.   55.   70.   85.  100. ]]
70
2
(10, 7)
[[  1.    2.    3.    4.    5.    6.    7.    8.    9.   10. ]
 [  2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25. ]
 [  4.    8.   12.   16.   20.   24.   28.   32.   36.   40. ]
 [  5.5  11.   16.5  22.   27.5  33.   38.5  44.   49.5  55. ]
 [  7.   14.   21.   28.   35.   42.   49.   56.   63.   70. ]
 [  8.5  17.   25.5  34.   42.5  51.   59.5  68.   76.5  85. ]
 [ 10.   20.   30.   40.   50.   60.   70.   80.   90.  100. ]]
70
2
(7, 10)


In [63]:
A = np.logspace(1, 2, 10).reshape(-1, 1) * np.logspace(1, 2, 7)

print(A)
print(A.size)
print(A.ndim)
print(A.shape)

print(A.T)
print(A.T.size)
print(A.T.ndim)
print(A.T.shape)

[[  100.           146.77992676   215.443469     316.22776602
    464.15888336   681.29206906  1000.        ]
 [  129.1549665    189.57356524   278.25594022   408.42386527
    599.48425032   879.92254357  1291.54966501]
 [  166.81005372   244.84367468   359.38136638   527.49970637
    774.26368268  1136.46366639  1668.1005372 ]
 [  215.443469     316.22776602   464.15888336   681.29206906
   1000.          1467.79926762  2154.43469003]
 [  278.25594022   408.42386527   599.48425032   879.92254357
   1291.54966501  1895.73565241  2782.55940221]
 [  359.38136638   527.49970637   774.26368268  1136.46366639
   1668.1005372   2448.43674682  3593.8136638 ]
 [  464.15888336   681.29206906  1000.          1467.79926762
   2154.43469003  3162.27766017  4641.58883361]
 [  599.48425032   879.92254357  1291.54966501  1895.73565241
   2782.55940221  4084.23865267  5994.84250319]
 [  774.26368268  1136.46366639  1668.1005372   2448.43674682
   3593.8136638   5274.9970637   7742.63682681]
 [ 1000.  

In [64]:
A = np.random.rand(10, 7)

print(A)
print(A.size)
print(A.ndim)
print(A.shape)

print(A.T)
print(A.T.size)
print(A.T.ndim)
print(A.T.shape)

[[0.51479624 0.59674515 0.54213112 0.53350713 0.17707744 0.5035085
  0.70148184]
 [0.67959304 0.71523424 0.8296788  0.73879798 0.54737177 0.13812933
  0.71086862]
 [0.6444473  0.59712852 0.3391094  0.67826656 0.04167398 0.48371564
  0.97439718]
 [0.30329682 0.9279446  0.31104255 0.20688682 0.38919667 0.71715115
  0.89158419]
 [0.00398837 0.55955812 0.92545136 0.03415206 0.57895298 0.28126045
  0.21187088]
 [0.47927651 0.04537957 0.48687571 0.97982048 0.90726657 0.97018136
  0.2672894 ]
 [0.71954706 0.20605838 0.92800356 0.2482384  0.12886652 0.98678809
  0.51836224]
 [0.55207423 0.05197718 0.49041415 0.39400171 0.45625446 0.6451356
  0.919815  ]
 [0.66456619 0.50263846 0.32650919 0.40883391 0.53692114 0.51483423
  0.73595107]
 [0.6994714  0.79849038 0.65751905 0.73116824 0.69819944 0.20772703
  0.6022803 ]]
70
2
(10, 7)
[[0.51479624 0.67959304 0.6444473  0.30329682 0.00398837 0.47927651
  0.71954706 0.55207423 0.66456619 0.6994714 ]
 [0.59674515 0.71523424 0.59712852 0.9279446  0.55955

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [74]:
A_ = A.flatten()
print(A_)
A__ = np.reshape(A_, (10, 7))
print(A__)

[0.51479624 0.59674515 0.54213112 0.53350713 0.17707744 0.5035085
 0.70148184 0.67959304 0.71523424 0.8296788  0.73879798 0.54737177
 0.13812933 0.71086862 0.6444473  0.59712852 0.3391094  0.67826656
 0.04167398 0.48371564 0.97439718 0.30329682 0.9279446  0.31104255
 0.20688682 0.38919667 0.71715115 0.89158419 0.00398837 0.55955812
 0.92545136 0.03415206 0.57895298 0.28126045 0.21187088 0.47927651
 0.04537957 0.48687571 0.97982048 0.90726657 0.97018136 0.2672894
 0.71954706 0.20605838 0.92800356 0.2482384  0.12886652 0.98678809
 0.51836224 0.55207423 0.05197718 0.49041415 0.39400171 0.45625446
 0.6451356  0.919815   0.66456619 0.50263846 0.32650919 0.40883391
 0.53692114 0.51483423 0.73595107 0.6994714  0.79849038 0.65751905
 0.73116824 0.69819944 0.20772703 0.6022803 ]
[[0.51479624 0.59674515 0.54213112 0.53350713 0.17707744 0.5035085
  0.70148184]
 [0.67959304 0.71523424 0.8296788  0.73879798 0.54737177 0.13812933
  0.71086862]
 [0.6444473  0.59712852 0.3391094  0.67826656 0.04167398

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [97]:
A = np.logspace(1, 2, 10).reshape(-1, 1) * np.logspace(1, 2, 15)
print(A)
print(A[3])
A[:, 4]

[[  100.           117.87686348   138.94954944   163.7893707
    193.06977289   227.58459261   268.26957953   316.22776602
    372.75937203   439.39705608   517.94746792   610.54022966
    719.685673     848.34289824  1000.        ]
 [  129.1549665    152.24382354   179.46024403   211.54210685
    249.3592005    293.93680434   346.48348557   408.42386527
    481.43724208   567.50312058   668.95487869   788.54302909
    929.50978988  1095.67698604  1291.54966501]
 [  166.81005372   196.63045929   231.78181806   273.21713724
    322.05979187   379.63398119   447.50062973   527.49970637
    621.80010873   732.95846528   863.98844948  1018.44248508
   1200.50805775  1415.12124429  1668.1005372 ]
 [  215.443469     253.95800383   299.35772947   352.87350208
    415.95621631   490.31614123   577.96928842   681.29206906
    803.08572214   946.65226031  1115.88399251  1315.36905044
   1550.51577983  1827.69936902  2154.43469003]
 [  278.25594022   327.99937478   386.63537522   455.75365341
   

array([ 193.06977289,  249.3592005 ,  322.05979187,  415.95621631,
        537.22811183,  693.85678787,  896.15050195, 1157.42288059,
       1494.86913371, 1930.69772888])

Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A
Gợi ý: tham khảo hàm apply_along_axis() đã học ở bài trước.

In [145]:
from scipy import stats

def mean(vector):
  return np.mean(vector)

def median(vector):
  return np.median(vector)

def mode(vector):
  return stats.mode(vector)

def var(vector):
  return np.var(vector)

def std(vector):
  return np.std(vector)

A = np.arange(1, 16).reshape(-1, 1) * np.arange(1, 11)
print(A)
print("ROW:")
print("mean:", np.apply_along_axis(mean, 1, A))
print("median:", np.apply_along_axis(median, 1, A))
print("mode:", np.apply_along_axis(mode, 1, A))
print("var:", np.apply_along_axis(var, 1, A))
print("std:", np.apply_along_axis(std, 1, A))
print("COLUMM:")
print("mean:", np.apply_along_axis(mean, 0, A))
print("median:", np.apply_along_axis(median, 0, A))
print("mode:", np.apply_along_axis(mode, 0, A))
print("var:", np.apply_along_axis(var, 0, A))
print("std:", np.apply_along_axis(std, 0, A))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 11  22  33  44  55  66  77  88  99 110]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 13  26  39  52  65  78  91 104 117 130]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 15  30  45  60  75  90 105 120 135 150]]
ROW:
mean: [ 5.5 11.  16.5 22.  27.5 33.  38.5 44.  49.5 55.  60.5 66.  71.5 77.
 82.5]
median: [ 5.5 11.  16.5 22.  27.5 33.  38.5 44.  49.5 55.  60.5 66.  71.5 77.
 82.5]
mode: [[[ 1]
  [ 1]]

 [[ 2]
  [ 1]]

 [[ 3]
  [ 1]]

 [[ 4]
  [ 1]]

 [[ 5]
  [ 1]]

 [[ 6]
  [ 1]]

 [[ 7]
  [ 1]]

 [[ 8]
  [ 1]]

 [[ 9]
  [ 1]]

 [[10]
  [ 1]]

 [[11]
  [ 1]]
